Buttons-pussycatdolls 100% quality.exe
indigenousfriends/itlct-website-redesign pull request #11
Opened 2024-01-16 19:51 UTC by CosmicStarfire

completed buttons much like Nicole completed the girl group, but lets be real, Nicole WAS the the girl group!

2024-01-17 16:16 UTC, tingjc approved these changes
Just need to ignore the button samples in index.html

2024-01-18 16:55 UTC, SolivanLau requested changes
This looks great - Since these styles are being used globally, can we move these styles into **global.css ** instead of its own css file?


We sure can!! - Miranda

2024-01-18 21:25 UTC, maxharrisnet requested changes

2024-01-18 21:25 UTC, maxharrisnet commented on css/buttons.css
> +a {
This looks really good! Can we move these styles to global.css so that we don't have to link in another style sheet?

2024-01-18 21:25 UTC, maxharrisnet commented on css/buttons.css
> +.button1 {
Did you create these buttons in html somewhere to test them?

2024-01-18 22:58 UTC, closed without merging

2024-01-18 22:58 UTC, CosmicStarfire commented
Thank you kindly all for the update! pushing my changes to global styles shortly!