Events and Programming Page
indigenousfriends/itlct-website-redesign pull request #12
Opened 2024-01-17 16:53 UTC by charlisable

finished coding events and programming page, please take a look

2024-01-18 21:16 UTC, maxharrisnet requested changes

2024-01-18 21:16 UTC, maxharrisnet commented on events.html
> +
Please add the footer here

2024-01-18 21:16 UTC, maxharrisnet commented on events.html
> +
Also, I just noticed a typo in the url for this page in the footer (via index.html). Can you please change `events.hmtl` -> `events.html`?

2024-01-18 21:16 UTC, maxharrisnet commented on events.html
> +  <title>If These Lands Could Talk - Events and Programming</title>
Thanks for adding the title. Should it be "Events and Programs" vs "... Programming"?

2024-01-18 21:16 UTC, maxharrisnet commented on events.html
> +  <!-- In a new branch, rename this page.css file to the name of that actual page (Example: home.css) -->
You can delete this comment

2024-01-18 21:16 UTC, maxharrisnet commented on events.html
> +          <img src="assets/images/pages/event-program/event.jpg" alt="">
These poster images need a max-width so that they don't take up too much space on certain screen sizes.

<img width="445" alt="Screen Shot 2024-01-18 at 11 50 40 AM" src="https://github.com/indigenousfriends/itlct-website-redesign/assets/704697/80e410a1-6b03-45b7-89e0-d766bba9959c">

2024-01-18 21:16 UTC, maxharrisnet commented on css/events.css
> +	color: var(--ONYX, #424241);
This var needs to be fixed

2024-01-18 21:16 UTC, maxharrisnet commented on css/events.css
> +	border-radius: 10px;
There are a number of places where we could replace hard-coded values with variables.

2024-01-22 14:34 UTC, charlisable commented on events.html
> +          <img src="assets/images/pages/event-program/event.jpg" alt="">
added a max-width of 350px to the event class, please let me know if this needs to be changed.

2024-01-22 18:10 UTC, SolivanLau requested changes
Hi @charlisable ! Thanks for a great start on the events page. Code looks clean and readable!

One request would be to review  and replace as many **numbered values** with appropriate variables:
- for irregular spacing and sizing numbers from figma, feel free to round up and find a similar variable to represent it!
- for magic numbers, feel free to use a rounded number for reference. 
- take a look at the shorthand for margin and padding properties and let's see if we can use vars for those as well!

thanks so much :)

2024-01-22 19:25 UTC, SolivanLau approved these changes
Thank you @charlisable for incorporating these variable changes! the page looks responsive and ready to go! great work :)

2024-01-22 19:38 UTC, maxharrisnet approved these changes
This looks perfect - excellent work! 🚀

2024-01-22 19:39 UTC, merged